# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Okctl < Formula
  desc "onkube.io CLI"
  homepage ""
  version "0.0.1-pre"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/onkube/onkube/releases/download/v0.0.1-pre/okctl-darwin-arm64.tar.gz"
      sha256 "5bc1edaec39cd4c1e95c6db90142e07074753eb69a9996c9e40958458a08bc03"
    end
    if Hardware::CPU.intel?
      url "https://github.com/onkube/onkube/releases/download/v0.0.1-pre/okctl-darwin-amd64.tar.gz"
      sha256 "c6f2b18ae9cb7d9daeee113c414879647b5898211acc54c7a64817e4944f8eae"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/onkube/onkube/releases/download/v0.0.1-pre/okctl-linux-amd64.tar.gz"
      sha256 "f19f6d5295e9fa5ad6fbb781c01f602c977f2a197cf57e2e81073a6f95a439f3"
    end
  end

  def install
    bin.install "okctl"
  end
end
