# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Okctl < Formula
  desc "onkube.io CLI"
  homepage ""
  version "0.0.1-pre5"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/onkube/homebrew-tap/releases/download/v0.0.1-pre5/okctl-darwin-arm64.tar.gz"
      sha256 "7a1d6a07f2e757d15265142eabaed2cf5ed4f31546a1e1aea5a463d7c6df84f6"
    end
    if Hardware::CPU.intel?
      url "https://github.com/onkube/homebrew-tap/releases/download/v0.0.1-pre5/okctl-darwin-amd64.tar.gz"
      sha256 "54349c738f95967b12fe85d81988d195c67c3201eff7a545a3bcf97816e46dc5"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/onkube/homebrew-tap/releases/download/v0.0.1-pre5/okctl-linux-amd64.tar.gz"
      sha256 "815e7324f926cfed7d8ead8108f8e11949d30fd575b24d5a1056e8519cd906f3"
    end
  end

  def install
    bin.install "okctl"
  end
end
