# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Onctl < Formula
  desc "onkube.io CLI"
  homepage ""
  version "0.0.18"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/onkube/homebrew-tap/releases/download/v0.0.18/onctl-darwin-arm64.tar.gz"
      sha256 "003a88a4bcf249196cde28e131d310ba8deb896f4caeae1822020ca46af35f35"

      def install
        bin.install "onctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/onkube/homebrew-tap/releases/download/v0.0.18/onctl-darwin-amd64.tar.gz"
      sha256 "347a0785febfd0dc92602a5b5f3702c1287c823ebb11328f202afc716fb2b0f2"

      def install
        bin.install "onctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/onkube/homebrew-tap/releases/download/v0.0.18/onctl-linux-amd64.tar.gz"
      sha256 "6ba2f387eb094e039f024194ce08e353bfe596196d62708845029b049f190328"

      def install
        bin.install "onctl"
      end
    end
  end
end
