# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Onctl < Formula
  desc "onkube.io CLI"
  homepage ""
  version "0.0.16"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onkube/homebrew-tap/releases/download/v0.0.16/onctl-darwin-amd64.tar.gz"
      sha256 "7ec8ed3e77f782e16b9c446c481dc65555d0052d1f6344bd6518395d6af8f1e2"

      def install
        bin.install "onctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onkube/homebrew-tap/releases/download/v0.0.16/onctl-darwin-arm64.tar.gz"
      sha256 "0638ab237ec126c467947ae8bcf56473dc6a74b507de145ca1b6d909aab8bf01"

      def install
        bin.install "onctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/onkube/homebrew-tap/releases/download/v0.0.16/onctl-linux-amd64.tar.gz"
      sha256 "63877e540b776cf51bdc57d332b6b6d890c118b801576da1a3c9d87e5f1d3654"

      def install
        bin.install "onctl"
      end
    end
  end
end
